"""
Django settings for tennis_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# Helpers
# ============================================================

def env_str(name: str, default: str = "") -> str:
    return (os.getenv(name) or default).strip()

def env_bool(name: str, default: bool = False) -> bool:
    v = (os.getenv(name) or "").strip().lower()
    if v == "":
        return default
    return v in ("1", "true", "t", "yes", "y", "on")

def env_int(name: str, default: int) -> int:
    value = (os.getenv(name) or "").strip()
    return int(value) if value else int(default)


# ============================================================
# Core
# ============================================================

# Railway本番は DEBUG を切る（ローカルでは env で DEBUG=1 など）
DEBUG = env_bool("DEBUG", default=True)

# 本番では公開済みの固定値へフォールバックしない。起動時に設定漏れを検出する。
_configured_secret_key = env_str("DJANGO_SECRET_KEY", "")
if not DEBUG and not _configured_secret_key:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY is required when DEBUG is false")
SECRET_KEY = _configured_secret_key or "django-insecure-local-development-only"

# 例: "INFO" / "DEBUG"
LOGGING_LEVEL = env_str("LOGGING_LEVEL", "DEBUG" if DEBUG else "INFO")


# ============================================================
# Hosts / CSRF
# ============================================================

ALLOWED_HOSTS = [
    "djangotennis-production.up.railway.app",
    "healthcheck.railway.app",  # Railway のヘルスチェックは Host: healthcheck.railway.app で来る
    "localhost",
    "127.0.0.1",
]

# Railway のドメインが変わる/増える可能性があるので env から追加できるようにする
# 例: RAILWAY_PUBLIC_DOMAIN=djangotennis-production.up.railway.app
RAILWAY_PUBLIC_DOMAIN = env_str("RAILWAY_PUBLIC_DOMAIN", "")
if RAILWAY_PUBLIC_DOMAIN and RAILWAY_PUBLIC_DOMAIN not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

# カンマ区切りで追加可能（任意）
# 例: ALLOWED_HOSTS_EXTRA=foo.example.com,bar.example.com
ALLOWED_HOSTS_EXTRA = env_str("ALLOWED_HOSTS_EXTRA", "")
if ALLOWED_HOSTS_EXTRA:
    for host in [h.strip() for h in ALLOWED_HOSTS_EXTRA.split(",") if h.strip()]:
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)

CSRF_TRUSTED_ORIGINS = [
    "https://djangotennis-production.up.railway.app",
]

if RAILWAY_PUBLIC_DOMAIN:
    origin = f"https://{RAILWAY_PUBLIC_DOMAIN}"
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

# 追加したい場合（任意）
# 例: CSRF_TRUSTED_ORIGINS=https://foo.example.com,https://bar.example.com
EXTRA_CSRF = env_str("CSRF_TRUSTED_ORIGINS", "")
if EXTRA_CSRF:
    for o in [x.strip() for x in EXTRA_CSRF.split(",") if x.strip()]:
        if o not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(o)

# ALLOWED_HOSTS_EXTRA で足した独自ドメインは CSRF 信頼オリジン(https)にも自動追加
# （カスタムドメイン切替時に POST が 403 になるのを防ぐ）
if ALLOWED_HOSTS_EXTRA:
    for host in [h.strip() for h in ALLOWED_HOSTS_EXTRA.split(",") if h.strip()]:
        origin = f"https://{host}"
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)

# 正規ドメインへの統一（旧ホスト→正規ホストへ 301）
# 例: CANONICAL_HOST=deucenet.app をセットすると旧 *.up.railway.app から寄せる
CANONICAL_HOST = env_str("CANONICAL_HOST", "")
# 旧ホスト一覧（ここに含まれるホストへのアクセスを CANONICAL_HOST へ301）。
# ※ healthcheck.railway.app は含めない（Railwayのヘルスチェックを壊さないため）
REDIRECT_HOSTS = ["djangotennis-production.up.railway.app"]
if RAILWAY_PUBLIC_DOMAIN and RAILWAY_PUBLIC_DOMAIN not in REDIRECT_HOSTS:
    REDIRECT_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)
# CANONICAL_HOST 自身は誤って入っていても除外
REDIRECT_HOSTS = [h for h in REDIRECT_HOSTS if h and h != CANONICAL_HOST]

# Reverse proxy 配下（Railway）で https 判定を正しくする
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Cloudflareからオリジンへ付与する秘密ヘッダー。設定準備後に明示的に有効化する。
ORIGIN_VERIFY_ENABLED = env_bool("ORIGIN_VERIFY_ENABLED", default=False)
ORIGIN_VERIFY_SECRET = env_str("ORIGIN_VERIFY_SECRET", "")

# Turnstileはキー設定と画面確認が完了するまで無効。Siteverifyは有効時に必須。
TURNSTILE_ENABLED = env_bool("TURNSTILE_ENABLED", default=False)
TURNSTILE_SITE_KEY = env_str("TURNSTILE_SITE_KEY", "")
TURNSTILE_SECRET_KEY = env_str("TURNSTILE_SECRET_KEY", "")
TURNSTILE_EXPECTED_HOSTNAME = env_str("TURNSTILE_EXPECTED_HOSTNAME", CANONICAL_HOST)
TURNSTILE_TIMEOUT_SECONDS = env_int("TURNSTILE_TIMEOUT_SECONDS", 5)
if TURNSTILE_ENABLED and (not TURNSTILE_SITE_KEY or not TURNSTILE_SECRET_KEY):
    raise ImproperlyConfigured(
        "TURNSTILE_ENABLED requires TURNSTILE_SITE_KEY and TURNSTILE_SECRET_KEY"
    )

# API・作成入口のレート制限。Redis接続後に本番で有効化する。
APP_RATE_LIMIT_ENABLED = env_bool("APP_RATE_LIMIT_ENABLED", default=False)
WRITE_RATE_LIMIT = env_int("WRITE_RATE_LIMIT", 120)
WRITE_RATE_WINDOW_SECONDS = env_int("WRITE_RATE_WINDOW_SECONDS", 60)
CLUB_CREATE_RATE_LIMIT = env_int("CLUB_CREATE_RATE_LIMIT", 3)
CLUB_CREATE_RATE_WINDOW_SECONDS = env_int("CLUB_CREATE_RATE_WINDOW_SECONDS", 3600)
DEMO_CREATE_RATE_LIMIT = env_int("DEMO_CREATE_RATE_LIMIT", 3)
DEMO_CREATE_RATE_WINDOW_SECONDS = env_int("DEMO_CREATE_RATE_WINDOW_SECONDS", 600)


# ============================================================
# Application definition
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tennis",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "tennis_project.middleware.OriginVerifyMiddleware",
    "tennis_project.middleware.CanonicalHostRedirectMiddleware",  # 旧ドメイン→正規ドメインへ301
    "django.middleware.gzip.GZipMiddleware",  # 動的HTMLレスポンスを gzip 圧縮（静的は WhiteNoise が担当）
    "whitenoise.middleware.WhiteNoiseMiddleware",  # static 配信
    "django.contrib.sessions.middleware.SessionMiddleware",
    "tennis_project.middleware.WriteRateLimitMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tennis_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tennis_project.wsgi.application"


# ============================================================
# Database
# ============================================================

# Railway では DATABASE_URL を使う（Postgres）
# ローカルでは DATABASE_URL が無いので SQLite で動く
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=False,
    )
}

REDIS_URL = env_str("REDIS_URL", "")
if not DEBUG and APP_RATE_LIMIT_ENABLED and not REDIS_URL:
    raise ImproperlyConfigured(
        "REDIS_URL is required when APP_RATE_LIMIT_ENABLED is true in production"
    )
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    # 開発・テスト用。本番の複数ワーカーではREDIS_URLを必須とする。
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "deucenet-local",
        }
    }


# ============================================================
# Password validation
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ============================================================
# Internationalization
# ============================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = env_str("TIME_ZONE", "Asia/Tokyo")  # 日本運用なら Tokyo 推奨
USE_I18N = True
USE_TZ = True


# ============================================================
# Static files (CSS, JavaScript, Images)
# ============================================================

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise 推奨（manifest 必須の本番運用）
STORAGES = {
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# どうしても manifest 不整合を一時回避したい場合だけ True にする（基本は触らない）
# WHITENOISE_MANIFEST_STRICT = env_bool("WHITENOISE_MANIFEST_STRICT", default=True)


# ============================================================
# Default primary key field type
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============================================================
# Logging
# ============================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {"handlers": ["console"], "level": LOGGING_LEVEL},
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },

        # ★追加：CSRF 403 の理由を出す
        "django.security.csrf": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
    },
}



# ============================================================
# Production security toggles
# ============================================================

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # ここはデフォルト(Lax)に任せる or 明示的にLax
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    SECURE_SSL_REDIRECT = True
    # ヘルスチェック /healthz は SSL リダイレクトの対象外（http のまま 200 を返す）
    SECURE_REDIRECT_EXEMPT = [r"^healthz$"]
    # HSTS：2回目以降は最初から https で来るのでリダイレクト往復が消える
    SECURE_HSTS_SECONDS = 31536000  # 1年
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
