"""
Django settings for tennis_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# Helpers
# ============================================================

def env_str(name: str, default: str = "") -> str:
    return (os.getenv(name) or default).strip()

def env_bool(name: str, default: bool = False) -> bool:
    v = (os.getenv(name) or "").strip().lower()
    if v == "":
        return default
    return v in ("1", "true", "t", "yes", "y", "on")


# ============================================================
# Core
# ============================================================

# 本番は必ず環境変数優先（Railwayで安全に運用するため）
# ローカル開発では未設定でも動くようにデフォルト値も用意
SECRET_KEY = env_str(
    "DJANGO_SECRET_KEY",
    "django-insecure-c@@+13zbt$x!abfun-8w+oiq1$lqnzrjzk(#cxn@&cu4*)$sdv",
)

# Railway本番は DEBUG を切る（ローカルでは env で DEBUG=1 など）
DEBUG = env_bool("DEBUG", default=False)

# 例: "INFO" / "DEBUG"
LOGGING_LEVEL = env_str("LOGGING_LEVEL", "DEBUG" if DEBUG else "INFO")


# ============================================================
# Hosts / CSRF
# ============================================================

ALLOWED_HOSTS = [
    "djangotennis-production.up.railway.app",
    "localhost",
    "127.0.0.1",
]

# Railway のドメインが変わる/増える可能性があるので env から追加できるようにする
# 例: RAILWAY_PUBLIC_DOMAIN=djangotennis-production.up.railway.app
RAILWAY_PUBLIC_DOMAIN = env_str("RAILWAY_PUBLIC_DOMAIN", "")
if RAILWAY_PUBLIC_DOMAIN and RAILWAY_PUBLIC_DOMAIN not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RAILWAY_PUBLIC_DOMAIN)

# カンマ区切りで追加可能（任意）
# 例: ALLOWED_HOSTS_EXTRA=foo.example.com,bar.example.com
ALLOWED_HOSTS_EXTRA = env_str("ALLOWED_HOSTS_EXTRA", "")
if ALLOWED_HOSTS_EXTRA:
    for host in [h.strip() for h in ALLOWED_HOSTS_EXTRA.split(",") if h.strip()]:
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)

CSRF_TRUSTED_ORIGINS = [
    "https://djangotennis-production.up.railway.app",
]

if RAILWAY_PUBLIC_DOMAIN:
    origin = f"https://{RAILWAY_PUBLIC_DOMAIN}"
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

# 追加したい場合（任意）
# 例: CSRF_TRUSTED_ORIGINS=https://foo.example.com,https://bar.example.com
EXTRA_CSRF = env_str("CSRF_TRUSTED_ORIGINS", "")
if EXTRA_CSRF:
    for o in [x.strip() for x in EXTRA_CSRF.split(",") if x.strip()]:
        if o not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(o)

# Reverse proxy 配下（Railway）で https 判定を正しくする
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# ============================================================
# Application definition
# ============================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tennis",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # static 配信
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tennis_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tennis_project.wsgi.application"


# ============================================================
# Database
# ============================================================

# Railway では DATABASE_URL を使う（Postgres）
# ローカルでは DATABASE_URL が無いので SQLite で動く
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=False,
    )
}


# ============================================================
# Password validation
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ============================================================
# Internationalization
# ============================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = env_str("TIME_ZONE", "Asia/Tokyo")  # 日本運用なら Tokyo 推奨
USE_I18N = True
USE_TZ = True


# ============================================================
# Static files (CSS, JavaScript, Images)
# ============================================================

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise 推奨（manifest 必須の本番運用）
STORAGES = {
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
}

# どうしても manifest 不整合を一時回避したい場合だけ True にする（基本は触らない）
# WHITENOISE_MANIFEST_STRICT = env_bool("WHITENOISE_MANIFEST_STRICT", default=True)


# ============================================================
# Default primary key field type
# ============================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============================================================
# Logging
# ============================================================

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "root": {"handlers": ["console"], "level": LOGGING_LEVEL},
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}


# ============================================================
# Production security toggles
# ============================================================

if not DEBUG:
    # Cookie を HTTPS 専用に
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # https へ強制（proxy下で https 判定できる前提）
    SECURE_SSL_REDIRECT = True

    # 推奨ヘッダ（必要なら有効化）
    # SECURE_HSTS_SECONDS = int(env_str("SECURE_HSTS_SECONDS", "0"))
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
    # SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", default=False)
