"""
base.html で常時読み込む CSS を1枚に結合して tennis/static/tennis/app.css を生成する。

リクエスト数削減のため。CSS に url() 相対参照は無く、結合先も同ディレクトリなので
パス崩れは起きない。読み込み順は base.html の <link> と同一にすること（カスケード維持）。

base 系 CSS を編集したら必ず再実行: `python manage.py bundle_css`
（本番では Railway のビルドで collectstatic 前に走らせると常に最新になる）
"""
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand

# base.html の <link> と同じ順序で（カスケードを変えないため厳守）
BASE_CSS = [
    "style.css",
    "calendar.css",
    "index.css",
    "admin.css",
    "base.css",
    "event.css",
    "schedule.css",
    "modal.css",
    "participants.css",
    "responsive.css",
]
OUTPUT = "app.css"


class Command(BaseCommand):
    help = "base.html 共通CSSを app.css に結合する"

    def handle(self, *args, **options):
        static_dir = Path(settings.BASE_DIR) / "tennis" / "static" / "tennis"
        parts = [
            "/* === AUTO-GENERATED by `manage.py bundle_css` — このファイルは直接編集しない === */\n"
        ]
        total = 0
        for name in BASE_CSS:
            path = static_dir / name
            if not path.exists():
                self.stderr.write(self.style.WARNING(f"見つかりません: {name}（スキップ）"))
                continue
            css = path.read_text(encoding="utf-8")
            total += len(css.encode("utf-8"))
            parts.append(f"\n/* ---- {name} ---- */\n{css}")

        out_path = static_dir / OUTPUT
        out_path.write_text("".join(parts), encoding="utf-8")
        size = out_path.stat().st_size
        self.stdout.write(self.style.SUCCESS(
            f"{OUTPUT} を生成: {len(BASE_CSS)}枚 → 1枚 ({size//1024}KB)"
        ))
