# Generated by Django 6.0 on 2025-12-19 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('public_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('admin_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubFlagDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_definitions', to='tennis.club')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('cancelled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tennis.club')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_token_kind', models.CharField(choices=[('public', 'public'), ('admin', 'admin')], max_length=10)),
                ('action', models.CharField(max_length=100)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tennis.club')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tennis.event')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_json', models.JSONField()),
                ('game_type', models.CharField(choices=[('doubles', 'Doubles'), ('singles', 'Singles')], max_length=10)),
                ('court_count', models.PositiveIntegerField()),
                ('round_count', models.PositiveIntegerField()),
                ('published', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_schedule', to='tennis.event')),
            ],
        ),
        migrations.CreateModel(
            name='MatchScheduleDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_json', models.JSONField(blank=True, null=True)),
                ('params_json', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_schedule_draft', to='tennis.event')),
            ],
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField()),
                ('court_no', models.PositiveIntegerField()),
                ('side_a_score', models.PositiveIntegerField(blank=True, null=True)),
                ('side_b_score', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tennis.matchschedule')),
            ],
            options={
                'ordering': ['round_no', 'court_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('is_fixed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tennis.club')),
            ],
            options={
                'ordering': ['-is_fixed', 'display_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('attendance', models.CharField(blank=True, choices=[('yes', '参加'), ('no', '不参加'), ('maybe', '未定')], max_length=10, null=True)),
                ('participates_match', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participants', to='tennis.event')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participants', to='tennis.member')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_on', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='tennis.eventparticipant')),
                ('flag_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_flags', to='tennis.clubflagdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='tennis.matchschedule')),
                ('original_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_from', to='tennis.eventparticipant')),
                ('substitute_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_to', to='tennis.eventparticipant')),
            ],
        ),
        migrations.AddIndex(
            model_name='clubflagdefinition',
            index=models.Index(fields=['club', 'is_active'], name='tennis_club_club_id_856c01_idx'),
        ),
        migrations.AddIndex(
            model_name='clubflagdefinition',
            index=models.Index(fields=['club', 'display_order'], name='tennis_club_club_id_cae5b2_idx'),
        ),
        migrations.AddConstraint(
            model_name='clubflagdefinition',
            constraint=models.UniqueConstraint(fields=('club', 'display_order'), name='uq_club_flag_definition_club_display_order'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['club', 'date'], name='tennis_even_club_id_c8630f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['club', 'created_at'], name='tennis_audi_club_id_9c7d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event', 'created_at'], name='tennis_audi_event_i_4ac77d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='tennis_audi_action_fc13ba_idx'),
        ),
        migrations.AddIndex(
            model_name='matchschedule',
            index=models.Index(fields=['published'], name='tennis_matc_publish_521cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='matchschedule',
            index=models.Index(fields=['locked'], name='tennis_matc_locked_dbb336_idx'),
        ),
        migrations.AddIndex(
            model_name='matchscore',
            index=models.Index(fields=['match_schedule', 'round_no'], name='tennis_matc_match_s_9674a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchscore',
            constraint=models.UniqueConstraint(fields=('match_schedule', 'round_no', 'court_no'), name='uq_match_score_schedule_round_court'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['club', 'is_fixed', 'is_active'], name='tennis_memb_club_id_d29261_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['club', 'last_seen_at'], name='tennis_memb_club_id_d46d52_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event', 'member'], name='tennis_even_event_i_a6226d_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event', 'attendance'], name='tennis_even_event_i_d982f7_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event', 'participates_match'], name='tennis_even_event_i_5a55db_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('event', 'member'), name='uq_event_participant_event_member_notnull'),
        ),
        migrations.AddIndex(
            model_name='participantflag',
            index=models.Index(fields=['flag_definition', 'is_on'], name='tennis_part_flag_de_77b49c_idx'),
        ),
        migrations.AddConstraint(
            model_name='participantflag',
            constraint=models.UniqueConstraint(fields=('event_participant', 'flag_definition'), name='uq_participant_flag_ep_flagdef'),
        ),
        migrations.AddIndex(
            model_name='substitution',
            index=models.Index(fields=['match_schedule', 'round_no'], name='tennis_subs_match_s_2b8d6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='substitution',
            constraint=models.UniqueConstraint(fields=('match_schedule', 'round_no', 'original_participant'), name='uq_substitution_schedule_round_original'),
        ),
    ]
