# Generated by Django 6.0 on 2025-12-13 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('place', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('public_token', models.CharField(editable=False, max_length=32, unique=True)),
                ('admin_token', models.CharField(editable=False, max_length=32, unique=True)),
                ('draft_schedule', models.JSONField(blank=True, null=True)),
                ('published_schedule', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('date',), name='uniq_event_per_day')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('attendance', models.CharField(choices=[('yes', '参加'), ('no', '不参加'), ('maybe', '未定')], default='yes', max_length=10)),
                ('level', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('participates_match', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tennis.event')),
            ],
            options={
                'unique_together': {('event', 'name')},
            },
        ),
    ]
