# Generated by Django 6.0 on 2025-12-09 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開始時間')),
                ('place', models.CharField(blank=True, max_length=200, verbose_name='場所')),
                ('note', models.TextField(blank=True, verbose_name='メモ')),
                ('public_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('admin_token', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前 / ニックネーム')),
                ('level', models.CharField(blank=True, max_length=50, verbose_name='レベル')),
                ('attendance', models.CharField(choices=[('yes', '参加'), ('no', '不参加'), ('maybe', '未定')], default='yes', max_length=10, verbose_name='出欠')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tennis.event')),
            ],
        ),
    ]
