# Generated by Django 6.0 on 2025-12-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='uniq_event_per_day',
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='level',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
