# Generated by Django 6.0 on 2025-12-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participates_match',
            field=models.BooleanField(default=True, verbose_name='試合に参加する'),
        ),
    ]
