# Generated by Django 6.0 on 2025-12-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
