# Generated by Django 6.0 on 2025-12-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0002_event_place'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='member',
            name='tennis_memb_club_id_d29261_idx',
        ),
        migrations.RemoveIndex(
            model_name='member',
            name='tennis_memb_club_id_d46d52_idx',
        ),
        migrations.AddField(
            model_name='member',
            name='member_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['club', 'is_fixed'], name='tennis_memb_club_id_bfa331_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['club', 'member_no'], name='tennis_memb_club_id_10e786_idx'),
        ),
        migrations.AddConstraint(
            model_name='member',
            constraint=models.UniqueConstraint(fields=('club', 'member_no'), name='uniq_member_no_per_club'),
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_seen_at',
        ),
    ]
