# Generated by Django 6.0 on 2025-12-13 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0002_remove_event_uniq_event_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='クラブ名')),
                ('public_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='公開トークン')),
                ('admin_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='幹事トークン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
        migrations.CreateModel(
            name='ClubFlagDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='フラグ名')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効（表示）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_key', models.CharField(max_length=50, verbose_name='試合キー')),
                ('score_text', models.CharField(blank=True, max_length=50, verbose_name='スコア')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'ordering': ['match_key', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='admin_token',
        ),
        migrations.RemoveField(
            model_name='event',
            name='public_token',
        ),
        migrations.RemoveField(
            model_name='event',
            name='published_schedule',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='event',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='level',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='participates_match',
        ),
        migrations.AddField(
            model_name='event',
            name='has_score',
            field=models.BooleanField(default=False, verbose_name='スコアあり'),
        ),
        migrations.AddField(
            model_name='event',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ロック日時'),
        ),
        migrations.AddField(
            model_name='event',
            name='locked_schedule',
            field=models.JSONField(blank=True, default=dict, verbose_name='対戦表（確定版）'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='participant',
            name='display_name',
            field=models.CharField(default='', max_length=50, verbose_name='表示名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(verbose_name='練習日'),
        ),
        migrations.AlterField(
            model_name='event',
            name='draft_schedule',
            field=models.JSONField(blank=True, default=dict, verbose_name='対戦表（下書き）'),
        ),
        migrations.AlterField(
            model_name='event',
            name='note',
            field=models.TextField(blank=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=255, verbose_name='場所'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開始時刻'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(choices=[('yes', '〇'), ('no', '×'), ('maybe', '？')], default='maybe', max_length=10, verbose_name='出欠')),
                ('participates_match', models.BooleanField(default=False, verbose_name='試合参加')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='tennis.event')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='tennis.participant')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False, verbose_name='チェック')),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='tennis.attendance')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tennis.club'),
        ),
        migrations.AddField(
            model_name='participant',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tennis.club'),
        ),
        migrations.AddField(
            model_name='clubflagdefinition',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_definitions', to='tennis.club'),
        ),
        migrations.AddField(
            model_name='attendanceflag',
            name='flag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_flags', to='tennis.clubflagdefinition'),
        ),
        migrations.AddField(
            model_name='matchscore',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='tennis.event'),
        ),
    ]
