# Generated by Django 6.0 on 2025-12-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0002_participant_participates_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='published_schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
