# Generated by Django 6.0 on 2025-12-10 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0003_event_published_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='フラグ名')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='表示順')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_definitions', to='tennis.event')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('event', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ParticipantFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False, verbose_name='フラグON')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_flags', to='tennis.flagdefinition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_flags', to='tennis.participant')),
            ],
            options={
                'unique_together': {('participant', 'flag')},
            },
        ),
    ]
