# Generated by Django 6.0 on 2025-12-24 12:22
from django.db import migrations

def fill_member_no(apps, schema_editor):
    Member = apps.get_model("tennis", "Member")

    club_ids = Member.objects.values_list("club_id", flat=True).distinct()

    for club_id in club_ids:
        qs = Member.objects.filter(club_id=club_id).order_by("id")
        n = 1
        for m in qs:
            if m.member_no is None:
                m.member_no = n
                m.save(update_fields=["member_no"])
            n += 1

def unfill_member_no(apps, schema_editor):
    Member = apps.get_model("tennis", "Member")
    Member.objects.update(member_no=None)

class Migration(migrations.Migration):
    dependencies = [
        ("tennis", "0003_remove_member_tennis_memb_club_id_d29261_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(fill_member_no, unfill_member_no),
    ]
