# Generated by Django 6.0 on 2025-12-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0003_club_clubflagdefinition_matchscore_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clubflagdefinition',
            constraint=models.UniqueConstraint(fields=('club', 'order'), name='uniq_flag_club_order'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('club', 'date'), name='uniq_event_club_date'),
        ),
        migrations.AddConstraint(
            model_name='matchscore',
            constraint=models.UniqueConstraint(fields=('event', 'match_key'), name='uniq_score_event_matchkey'),
        ),
    ]
