# Generated by Django 6.0 on 2025-12-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0004_fill_member_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_no',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
