# Generated by Django 6.0 on 2025-12-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0004_flagdefinition_participantflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='draft_schedule',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
