# Generated by Django 6.0 on 2025-12-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0005_alter_member_member_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='flag_input_mode',
            field=models.CharField(choices=[('check', 'チェックボックス'), ('digit', '数字(1桁)')], default='check', max_length=10),
        ),
        migrations.AddField(
            model_name='participantflag',
            name='value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
