# Generated by Django 6.0 on 2025-12-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0006_club_flag_input_mode_participantflag_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubflagdefinition',
            name='input_mode',
            field=models.CharField(choices=[('check', 'チェック'), ('digit', '数字(1桁)')], default='check', max_length=10),
        ),
        migrations.AlterField(
            model_name='clubflagdefinition',
            name='display_order',
            field=models.PositiveIntegerField(),
        ),
    ]
