# Generated by Django 6.0 on 2025-12-30 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0007_clubflagdefinition_input_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDisplaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_flags', models.BooleanField(default=True)),
                ('show_class', models.BooleanField(default=True)),
                ('show_schedule', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_setting', to='tennis.event')),
            ],
        ),
    ]
