# Generated by Django 6.0 on 2025-12-31 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0009_clubmemberclass_member_member_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubmemberclass',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='event_member_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participants', to='tennis.clubmemberclass'),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='clubmemberclass',
            index=models.Index(fields=['club', 'is_active'], name='tennis_club_club_id_bcfb00_idx'),
        ),
        migrations.AddIndex(
            model_name='clubmemberclass',
            index=models.Index(fields=['club', 'display_order'], name='tennis_club_club_id_7e0493_idx'),
        ),
    ]
