# Generated by Django 6.0 on 2026-01-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0010_alter_clubmemberclass_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipant',
            name='event_member_class',
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='class_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
