# Generated by Django 6.0 on 2026-01-04 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0011_remove_eventparticipant_event_member_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='event_member_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_participants', to='tennis.clubmemberclass'),
        ),
    ]
