# Generated by Django 6.0 on 2026-01-04 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0013_backfill_event_member_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFlagDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField()),
                ('input_mode', models.CharField(choices=[('check', 'チェック'), ('digit', '数字(1桁)')], default='check', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='participantflag',
            name='uq_participant_flag_ep_flagdef',
        ),
        migrations.RemoveIndex(
            model_name='participantflag',
            name='tennis_part_flag_de_77b49c_idx',
        ),
        migrations.AddField(
            model_name='participantflag',
            name='club_flag_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_flags', to='tennis.clubflagdefinition'),
        ),
        migrations.AddField(
            model_name='eventflagdefinition',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_flag_definitions', to='tennis.event'),
        ),
        migrations.AddField(
            model_name='participantflag',
            name='event_flag_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_flags', to='tennis.eventflagdefinition'),
        ),
        migrations.AddIndex(
            model_name='participantflag',
            index=models.Index(fields=['club_flag_definition', 'is_on'], name='tennis_part_club_fl_1d9d92_idx'),
        ),
        migrations.AddIndex(
            model_name='participantflag',
            index=models.Index(fields=['event_flag_definition', 'is_on'], name='tennis_part_event_f_0c07a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='participantflag',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('club_flag_definition__isnull', False), ('event_flag_definition__isnull', True)), models.Q(('club_flag_definition__isnull', True), ('event_flag_definition__isnull', False)), _connector='OR'), name='ck_participant_flag_exactly_one_definition'),
        ),
        migrations.AddConstraint(
            model_name='participantflag',
            constraint=models.UniqueConstraint(condition=models.Q(('club_flag_definition__isnull', False)), fields=('event_participant', 'club_flag_definition'), name='uq_participant_flag_ep_clubdef'),
        ),
        migrations.AddConstraint(
            model_name='participantflag',
            constraint=models.UniqueConstraint(condition=models.Q(('event_flag_definition__isnull', False)), fields=('event_participant', 'event_flag_definition'), name='uq_participant_flag_ep_eventdef'),
        ),
        migrations.RemoveField(
            model_name='participantflag',
            name='flag_definition',
        ),
        migrations.AddIndex(
            model_name='eventflagdefinition',
            index=models.Index(fields=['event', 'is_active'], name='tennis_even_event_i_297ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='eventflagdefinition',
            index=models.Index(fields=['event', 'display_order'], name='tennis_even_event_i_d91e23_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventflagdefinition',
            constraint=models.UniqueConstraint(fields=('event', 'display_order'), name='uq_event_flag_definition_event_display_order'),
        ),
    ]
