# Generated by Django 6.0 on 2026-01-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0014_eventflagdefinition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdisplaysetting',
            name='show_event_flags',
            field=models.BooleanField(default=False),
        ),
    ]
