# Generated by Django 6.0 on 2026-05-26 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0015_eventdisplaysetting_show_event_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='member_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
