# Generated by Django 6.0 on 2026-05-30 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0016_eventparticipant_member_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubDisplaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_flags', models.BooleanField(default=True)),
                ('show_event_flags', models.BooleanField(default=False)),
                ('show_class', models.BooleanField(default=True)),
                ('show_schedule', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_setting', to='tennis.club')),
            ],
        ),
    ]
