# Generated by Django 6.0 on 2026-06-03 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0017_clubdisplaysetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubRankingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset', models.CharField(choices=[('winrate', '勝率重視型'), ('points', '勝ち点制'), ('wins', '勝利数重視型')], default='winrate', max_length=10)),
                ('count_draws', models.BooleanField(default=False)),
                ('points_win', models.DecimalField(decimal_places=1, default=3, max_digits=4)),
                ('points_draw', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('points_loss', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('min_matches', models.PositiveIntegerField(default=6)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_setting', to='tennis.club')),
            ],
        ),
    ]
