# Generated by Django 6.0 on 2026-06-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0018_clubrankingsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrankingsetting',
            name='period_days',
            field=models.PositiveIntegerField(default=90),
        ),
    ]
