# Generated by Django 6.0 on 2026-06-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0019_clubrankingsetting_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='demo_seeded_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
