# Generated by Django 6.0 on 2026-06-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0020_club_demo_seeded_on_club_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='demo_last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
