# Generated by Django 6.0 on 2026-06-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0021_club_demo_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='demo_seed_version',
            field=models.IntegerField(default=0),
        ),
    ]
