# Generated by Django 6.0 on 2026-07-07 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0022_club_demo_seed_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubOrganizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizers', to='tennis.club')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizer_roles', to='tennis.member')),
            ],
            options={
                'indexes': [models.Index(fields=['club'], name='tennis_club_club_id_a19b7d_idx'), models.Index(fields=['email'], name='tennis_club_email_a8ce56_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('member__isnull', False)), fields=('club', 'member'), name='uniq_organizer_per_member')],
            },
        ),
    ]
