# Generated by Django 6.0 on 2026-07-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0023_cluborganizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'key', 'created_at'], name='tennis_emai_scope_ba7ef1_idx')],
            },
        ),
    ]
