# Generated by Django 6.0 on 2026-09-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0027_club_last_accessed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubrankingsetting',
            name='period_mode',
            field=models.CharField(choices=[('rolling', '過去日数'), ('cycle', '期間を区切る')], default='rolling', max_length=10),
        ),
        migrations.AddField(
            model_name='clubrankingsetting',
            name='period_months',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='clubrankingsetting',
            name='period_start_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='clubrankingsetting',
            name='period_start_month',
            field=models.PositiveSmallIntegerField(default=4),
        ),
    ]
