# Generated by Django 6.0 on 2026-09-15 08:52

from django.db import migrations, models


def backfill_registered_by_email(apps, schema_editor):
    Club = apps.get_model('tennis', 'Club')
    ClubOrganizer = apps.get_model('tennis', 'ClubOrganizer')

    for club in Club.objects.filter(registered_by_email='').iterator():
        first_organizer = (
            ClubOrganizer.objects
            .filter(club_id=club.pk)
            .order_by('created_at', 'id')
            .first()
        )
        if first_organizer:
            email = (first_organizer.email or first_organizer.pending_email or '').strip()
            if email:
                Club.objects.filter(pk=club.pk).update(registered_by_email=email)


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0028_ranking_period_modes'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='registered_by_email',
            field=models.EmailField(blank=True, default='', editable=False, max_length=254),
        ),
        migrations.RunPython(backfill_registered_by_email, migrations.RunPython.noop),
    ]
