# Generated by Django 6.0 on 2026-09-24 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis', '0029_club_registered_by_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=64)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('first_event_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tennis.club')),
                ('organizer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tennis.cluborganizer')),
            ],
        ),
    ]
